In [1]:
# convention for import to get shortened name space
import numpy as np
import xarray as xr

In [2]:
#create some sample temperature data for use
data = 283 + 5 * np.random.randn(5,3,4)
data

array([[[275.51033964, 278.72561277, 281.89066078, 288.89064182],
        [281.83514848, 284.19100327, 289.89789492, 295.27420436],
        [288.4418246 , 270.50994738, 285.47007866, 280.39117654]],

       [[279.4530169 , 281.71502823, 273.88741798, 286.09352245],
        [280.50059508, 277.41928037, 271.66110889, 290.23184711],
        [282.18581616, 287.45066771, 287.77309364, 281.51360415]],

       [[281.17533129, 286.50523214, 283.91133494, 286.39835971],
        [281.62610535, 277.05202487, 286.18255539, 286.99580456],
        [289.76571658, 279.12882979, 277.77954947, 286.93873667]],

       [[275.57192139, 282.43790603, 286.68562074, 287.28156838],
        [281.84999638, 280.93218122, 272.54730113, 288.11471721],
        [286.54332385, 283.41162433, 267.85219822, 277.69270662]],

       [[289.87869954, 280.16419997, 283.64066807, 274.78561911],
        [272.37500495, 272.37392826, 283.00432383, 283.06908089],
        [287.6225595 , 289.04080175, 276.2571787 , 275.81245352]]])

In [3]:
#create an xarray from the data we made
temp = xr.DataArray(data)
temp

<xarray.DataArray (dim_0: 5, dim_1: 3, dim_2: 4)>
array([[[275.51033964, 278.72561277, 281.89066078, 288.89064182],
        [281.83514848, 284.19100327, 289.89789492, 295.27420436],
        [288.4418246 , 270.50994738, 285.47007866, 280.39117654]],

       [[279.4530169 , 281.71502823, 273.88741798, 286.09352245],
        [280.50059508, 277.41928037, 271.66110889, 290.23184711],
        [282.18581616, 287.45066771, 287.77309364, 281.51360415]],

       [[281.17533129, 286.50523214, 283.91133494, 286.39835971],
        [281.62610535, 277.05202487, 286.18255539, 286.99580456],
        [289.76571658, 279.12882979, 277.77954947, 286.93873667]],

       [[275.57192139, 282.43790603, 286.68562074, 287.28156838],
        [281.84999638, 280.93218122, 272.54730113, 288.11471721],
        [286.54332385, 283.41162433, 267.85219822, 277.69270662]],

       [[289.87869954, 280.16419997, 283.64066807, 274.78561911],
        [272.37500495, 272.37392826, 283.00432383, 283.06908089],
        [287.6225595 , 289.04080175, 276.2571787 , 275.81245352]]])
Dimensions without coordinates: dim_0, dim_1, dim_2

In [4]:
# now we can add some dimensions
temp = xr.DataArray(data, dims = ['time', 'lat', 'lon'])
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[275.51033964, 278.72561277, 281.89066078, 288.89064182],
        [281.83514848, 284.19100327, 289.89789492, 295.27420436],
        [288.4418246 , 270.50994738, 285.47007866, 280.39117654]],

       [[279.4530169 , 281.71502823, 273.88741798, 286.09352245],
        [280.50059508, 277.41928037, 271.66110889, 290.23184711],
        [282.18581616, 287.45066771, 287.77309364, 281.51360415]],

       [[281.17533129, 286.50523214, 283.91133494, 286.39835971],
        [281.62610535, 277.05202487, 286.18255539, 286.99580456],
        [289.76571658, 279.12882979, 277.77954947, 286.93873667]],

       [[275.57192139, 282.43790603, 286.68562074, 287.28156838],
        [281.84999638, 280.93218122, 272.54730113, 288.11471721],
        [286.54332385, 283.41162433, 267.85219822, 277.69270662]],

       [[289.87869954, 280.16419997, 283.64066807, 274.78561911],
        [272.37500495, 272.37392826, 283.00432383, 283.06908089],
        [287.6225595 , 289.04080175, 276.2571787 , 275.81245352]]])
Dimensions without coordinates: time, lat, lon

In [6]:
# lets make an array of times using datetime
import pandas as pd
times = pd.date_range('2018-01-01' ,periods = 5)
times

DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05'],
              dtype='datetime64[ns]', freq='D')

In [7]:
# bring in some sample lat lons
lons = np.linspace(-120,-60,4)
lats = np.linspace(25,55,3)

In [8]:
temp = xr.DataArray(data, coords = [times,lats,lons],dims = ['time','lat','lon'])
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[275.51033964, 278.72561277, 281.89066078, 288.89064182],
        [281.83514848, 284.19100327, 289.89789492, 295.27420436],
        [288.4418246 , 270.50994738, 285.47007866, 280.39117654]],

       [[279.4530169 , 281.71502823, 273.88741798, 286.09352245],
        [280.50059508, 277.41928037, 271.66110889, 290.23184711],
        [282.18581616, 287.45066771, 287.77309364, 281.51360415]],

       [[281.17533129, 286.50523214, 283.91133494, 286.39835971],
        [281.62610535, 277.05202487, 286.18255539, 286.99580456],
        [289.76571658, 279.12882979, 277.77954947, 286.93873667]],

       [[275.57192139, 282.43790603, 286.68562074, 287.28156838],
        [281.84999638, 280.93218122, 272.54730113, 288.11471721],
        [286.54332385, 283.41162433, 267.85219822, 277.69270662]],

       [[289.87869954, 280.16419997, 283.64066807, 274.78561911],
        [272.37500495, 272.37392826, 283.00432383, 283.06908089],
        [287.6225595 , 289.04080175, 276.2571787 , 275.81245352]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

In [10]:
#also for some attribute metadata
temp.attrs['units'] = 'kelvin'
temp.attrs['standard_name'] = 'air_temperature'
temp

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[275.51033964, 278.72561277, 281.89066078, 288.89064182],
        [281.83514848, 284.19100327, 289.89789492, 295.27420436],
        [288.4418246 , 270.50994738, 285.47007866, 280.39117654]],

       [[279.4530169 , 281.71502823, 273.88741798, 286.09352245],
        [280.50059508, 277.41928037, 271.66110889, 290.23184711],
        [282.18581616, 287.45066771, 287.77309364, 281.51360415]],

       [[281.17533129, 286.50523214, 283.91133494, 286.39835971],
        [281.62610535, 277.05202487, 286.18255539, 286.99580456],
        [289.76571658, 279.12882979, 277.77954947, 286.93873667]],

       [[275.57192139, 282.43790603, 286.68562074, 287.28156838],
        [281.84999638, 280.93218122, 272.54730113, 288.11471721],
        [286.54332385, 283.41162433, 267.85219822, 277.69270662]],

       [[289.87869954, 280.16419997, 283.64066807, 274.78561911],
        [272.37500495, 272.37392826, 283.00432383, 283.06908089],
        [287.6225595 , 289.04080175, 276.2571787 , 275.81245352]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [11]:
# now using a mathematical operator with a data array
#Example: Kelvin to Celcius
temp - 273.15

<xarray.DataArray (time: 5, lat: 3, lon: 4)>
array([[[ 2.36033964,  5.57561277,  8.74066078, 15.74064182],
        [ 8.68514848, 11.04100327, 16.74789492, 22.12420436],
        [15.2918246 , -2.64005262, 12.32007866,  7.24117654]],

       [[ 6.3030169 ,  8.56502823,  0.73741798, 12.94352245],
        [ 7.35059508,  4.26928037, -1.48889111, 17.08184711],
        [ 9.03581616, 14.30066771, 14.62309364,  8.36360415]],

       [[ 8.02533129, 13.35523214, 10.76133494, 13.24835971],
        [ 8.47610535,  3.90202487, 13.03255539, 13.84580456],
        [16.61571658,  5.97882979,  4.62954947, 13.78873667]],

       [[ 2.42192139,  9.28790603, 13.53562074, 14.13156838],
        [ 8.69999638,  7.78218122, -0.60269887, 14.96471721],
        [13.39332385, 10.26162433, -5.29780178,  4.54270662]],

       [[16.72869954,  7.01419997, 10.49066807,  1.63561911],
        [-0.77499505, -0.77607174,  9.85432383,  9.91908089],
        [14.4725595 , 15.89080175,  3.1071787 ,  2.66245352]]])
Coordinates:
  * time     (time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0

In [12]:
# you can use the .sel method to select portions of data based on coordinate values!! VERY IMPORTANT FOR HERE
temp.sel(time = '2018-01-02')

<xarray.DataArray (lat: 3, lon: 4)>
array([[279.4530169 , 281.71502823, 273.88741798, 286.09352245],
       [280.50059508, 277.41928037, 271.66110889, 290.23184711],
       [282.18581616, 287.45066771, 287.77309364, 281.51360415]])
Coordinates:
    time     datetime64[ns] 2018-01-02
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature

In [13]:
# .sel also has the ability to perform nearest neighbor interpolation, using an optional tolerance
from datetime import timedelta
temp.sel(time = '2018-01-07', method = 'nearest',tolerance = timedelta(days=2))

<xarray.DataArray (lat: 3, lon: 4)>
array([[289.87869954, 280.16419997, 283.64066807, 274.78561911],
       [272.37500495, 272.37392826, 283.00432383, 283.06908089],
       [287.6225595 , 289.04080175, 276.2571787 , 275.81245352]])
Coordinates:
    time     datetime64[ns] 2018-01-05
  * lat      (lat) float64 25.0 40.0 55.0
  * lon      (lon) float64 -120.0 -100.0 -80.0 -60.0
Attributes:
    units:          kelvin
    standard_name:  air_temperature