In [1]:
#xarray practice
#customary imports
import numpy as np
import pandas as pd
import xarray as xr

In [3]:
np.random.seed(123)
size = 4
temp = 15 + 10* np.random.randn(size)
lat = np.random.uniform(low = -90, high = 90,size = size)
lon = np.random.uniform(low = -180, high = 180, size = size)
#round to 2 digits after decimal
temp, lat, lon, = np.around([temp, lat, lon], decimals = 2)

In [7]:
# how to represent this data in Pandas
# 1- dataframe
df = pd.DataFrame({'temp':temp, 'lat':lat, 'lon': lon})
df

temp    lat    lon
0   4.14  39.50  -6.86
1  24.97 -13.84 -38.84
2  17.83  86.54 -56.46
3  -0.06  33.27  82.46

In [10]:
# now we can create a data array from this. There are four ways to do this.
#1. Create a data array from a series, with a two-level index = idx
idx = pd.MultiIndex.from_arrays(arrays = [lat,lon],names = ['lat','lon'])
s = pd.Series(data = temp, index = idx)
s
# use from_series method
da = xr.DataArray.from_series(s)
da

<xarray.DataArray (lat: 4, lon: 4)>
array([[  nan, 24.97,   nan,   nan],
       [  nan,   nan,   nan, -0.06],
       [  nan,   nan,  4.14,   nan],
       [17.83,   nan,   nan,   nan]])
Coordinates:
  * lat      (lat) float64 -13.84 33.27 39.5 86.54
  * lon      (lon) float64 -56.46 -38.84 -6.86 82.46

In [11]:
df_pv = df.pivot(index = 'lat', columns = 'lon')
#drop the first of columns as its not necessary
df_pv = df_pv.droplevel(0, axis = 1)
df_pv

lon     -56.46  -38.84  -6.86    82.46
lat                                   
-13.84     NaN   24.97     NaN     NaN
 33.27     NaN     NaN     NaN   -0.06
 39.50     NaN     NaN    4.14     NaN
 86.54   17.83     NaN     NaN     NaN

In [12]:
# now the data has been pivoted, and a data array can be produced
da = xr.DataArray(data = df_pv)
da

<xarray.DataArray (lat: 4, lon: 4)>
array([[  nan, 24.97,   nan,   nan],
       [  nan,   nan,   nan, -0.06],
       [  nan,   nan,  4.14,   nan],
       [17.83,   nan,   nan,   nan]])
Coordinates:
  * lat      (lat) float64 -13.84 33.27 39.5 86.54
  * lon      (lon) float64 -56.46 -38.84 -6.86 82.46

In [14]:
#create a data array usign a constructor
#This is the way to construct a data array manually

# get pivoted data as 2-d array (4,4)

temp_2d = df_pv.values
da = xr.DataArray(data = temp_2d, dims = ['lat','lon'], coords = [lat,lon])
da

<xarray.DataArray (lat: 4, lon: 4)>
array([[  nan, 24.97,   nan,   nan],
       [  nan,   nan,   nan, -0.06],
       [  nan,   nan,  4.14,   nan],
       [17.83,   nan,   nan,   nan]])
Coordinates:
  * lat      (lat) float64 39.5 -13.84 86.54 33.27
  * lon      (lon) float64 -6.86 -38.84 -56.46 82.46

In [23]:
np.random.seed(123)
shape = (1,4) #needs to be 2d could be (2,2) or (4,1)
# all three arrays have the same shape
temp = 15+10*np.random.randn(*shape)
lat = np.random.uniform(low = -90, high = 90, size = shape)
lon = np.random.uniform(low = -180, high = 180, size = shape)
#round to two digits after decimal
temp, lat, lon = np.around([temp, lat,lon],decimals = 2)


In [25]:
da = xr.DataArray(data = temp,coords={'lat':(['x','y'],lat),'lon': (['x','y'],lon)},dims = ['x','y'])

In [26]:
da

<xarray.DataArray (x: 1, y: 4)>
array([[ 4.14, 24.97, 17.83, -0.06]])
Coordinates:
    lat      (x, y) float64 39.5 -13.84 86.54 33.27
    lon      (x, y) float64 -6.86 -38.84 -56.46 82.46
Dimensions without coordinates: x, y